# Generated by Django 2.2.15 on 2020-08-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, verbose_name='STRONG POINT'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='THUMBNAILS'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='VIDEO'),
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='NAME')),
                ('text', models.TextField(verbose_name='SCOUT')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='profilex.Post')),
            ],
        ),
    ]
